version: '3.9'
services:
  database:
    image: 'postgres'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'twitter-clone'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '54032:5432'
